### ISSUE TITLE
Question about plugin

### ISSUE THREAD

**Issue by lostsoul6** [GabrielBigardi/CS2-AutoBalancePlugin#2]
Hi there , I don't understand what this means :  

Default mode: grabs the team with the most players and change them to the other team .

Does it mean it swaps the whole CT team and T team or just transfers 1-2 players to the other team so that they are equal?

**Comment by GabrielBigardi** [comment]
Hello, the default mode works as any auto-balance, it checks for the team with most players, and grab X players from that team and transfer to the other so they get equal number of players.
There is also the scramble mode, which is useful for retake servers where teams are random every round and auto-balanced.

**Comment by lostsoul6** [comment]
@GabrielBigardi , the default cs2 auto balance is very delayed and takes 2-3 rounds to balance . this plugin solves that issue and instantly auto balance the team? also auto balance should be at round start right ? I have a casual server not a retake server .

**Comment by GabrielBigardi** [comment]
> @GabrielBigardi , the default cs2 auto balance is very delayed and takes 2-3 rounds to balance . this plugin solves that issue and instantly auto balance the team? also auto balance should be at round start right ? I have a casual server not a retake server .

Yes, it auto-balances on round end/start, its configurable, for a casual server the default settings should be fine, but its been a while since i don't update this plugin to the latest CSSharp version, so i'm not 100% sure.

**Comment by GabrielBigardi** [comment]
Closing the issue as it's been inactive for a month, please feel free to open another issue if you want.
