### ISSUE TITLE
how can i set for aim_ and awp_ maps

### ISSUE THREAD

**Issue by 220352008** [GabrielBigardi/CS2-AutoBalancePlugin#3]
Hi, im using this plugin and working perfectly. But my server is running with multimod and i want to use only aim_ and awp_ maps. How can i do that?

**Comment by GabrielBigardi** [comment]
Hi, unfortunately there is no way of choosing map prefixes to enable it, you'll need to use another plugin for enabling plugins only on certain maps or make changes in the source code.

**Comment by 220352008** [comment]
what kind of code should i add to the source code?

**Comment by GabrielBigardi** [comment]
I'm not a C# teacher, user should be able to makes changes to the source code by themselves.
