### ISSUE TITLE
bad auto balance

### ISSUE THREAD

**Issue by mayersgamer** [GabrielBigardi/CS2-AutoBalancePlugin#4]
switch after round end and players kill each other after round end 
shoud be the switch at start imediatly like the valve auto balance default

**Comment by GabrielBigardi** [comment]
Hi, you can change the config to make this happen, just like the documentation says:

> "BalanceOnRoundStart": false, // Setting that to true will make the auto-balance happen upon round start (default: on round end)

**Comment by mayersgamer** [comment]
but when it switch at the start the player team doesnt change , it just teleport him to the other team spawn .
